global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: conmon
    metrics_path: /metrics
    static_configs:
      - targets:
          - conmon:9109

  - job_name: pushgateway
    honor_labels: true
    metrics_path: /metrics
    static_configs:
      - targets:
          - pushgateway:9091
